#!/usr/bin/env ruby

require 'uri'
require 'jira'
require 'net/http'
require_relative 'jira-utils.rb'
require_relative 'irc-utils.rb'

JiraUtils.username = ""
JiraUtils.password = ""

change_url   = ARGV[ARGV.index('--change-url')+1]
project_name = ARGV[ARGV.index('--project')+1]
commit       = ARGV[ARGV.index('--commit')+1]

commit_description = `git log #{commit}^..#{commit}`.strip
commit_author = `git log --format=%an #{commit}^..#{commit}`.strip

if task_id = JiraUtils.extract_issue_id(commit_description)
    task_link = JiraUtils.issue_uri_str(task_id)
    task_info = JiraUtils.issue_info(task_id)

    message = "_".color(:green,:green)+"[gerrit][merge]".bold
    message += " #{commit_author} #{change_url} #{task_link} #{task_info[:summary]}"

    IRCUtils.post(message)
end

